services:
  - type: web
    name: srec-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: JWT_SECRET
        generateValue: true
