'use client';

import React, { useState, useEffect } from 'react';
import {
  Users, CalendarCheck, CheckCircle2, AlertTriangle, XCircle,
  Download, Search, BookOpen, Layers, FileSpreadsheet
} from 'lucide-react';
import { useAuth } from '@/lib/auth-context';
import {
  AVAILABLE_SUBJECTS,
  getAllCandidatesAttendance,
  CandidateAttendanceItem,
} from '@/lib/attendance-store';

export default function FacultyAllCandidatesPage() {
  const { user } = useAuth();
  const facultyName = user?.full_name || 'Dr. K. Subba Reddy';
  const facultyId = user?.user_code || 'SREC-FAC-0104';
  const facultyDept = user?.department_name || 'Computer Science & Engineering';

  const [candidateSearch, setCandidateSearch] = useState('');
  const [selectedSubjectFilter, setSelectedSubjectFilter] = useState('ALL');
  const [selectedSectionFilter, setSelectedSectionFilter] = useState('ALL');
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  useEffect(() => {
    const handleUpdate = () => setRefreshTrigger((prev) => prev + 1);
    window.addEventListener('srec_attendance_updated', handleUpdate);
    window.addEventListener('storage', handleUpdate);
    return () => {
      window.removeEventListener('srec_attendance_updated', handleUpdate);
      window.removeEventListener('storage', handleUpdate);
    };
  }, []);

  const allCandidatesData = getAllCandidatesAttendance(
    selectedSubjectFilter === 'ALL' ? undefined : selectedSubjectFilter,
    selectedSectionFilter === 'ALL' ? undefined : selectedSectionFilter
  );

  const filteredCandidates = allCandidatesData.filter((c) => {
    const q = candidateSearch.toLowerCase();
    return c.name.toLowerCase().includes(q) || c.roll.toLowerCase().includes(q);
  });

  const totalCandidatesCount = filteredCandidates.length;
  const avgAttendance =
    totalCandidatesCount > 0
      ? Math.round(
          (filteredCandidates.reduce((acc, c) => acc + c.percentage, 0) / totalCandidatesCount) * 10
        ) / 10
      : 0;
  const shortageCandidates = filteredCandidates.filter((c) => c.percentage < 75);
  const goodStandingCandidates = filteredCandidates.filter((c) => c.percentage >= 75);

  const exportCandidatesReport = (items: CandidateAttendanceItem[]) => {
    if (items.length === 0) return;

    const csvRows: any[][] = [
      ['SANTHIRAM ENGINEERING COLLEGE (AUTONOMOUS) - NANDYAL'],
      ['ALL CANDIDATES ATTENDANCE ANALYTICS REPORT'],
      [''],
      ['Generated By Faculty', `"${facultyName}" (${facultyId})`],
      ['Department', `"${facultyDept}"`],
      ['Total Records', items.length],
      ['Generated On', `"${new Date().toLocaleString()}"`],
      [''],
      [
        'Roll Number',
        'Student Name',
        'Class Section',
        'Department',
        'Subject Code',
        'Subject Name',
        'Total Classes',
        'Attended Classes',
        'Absent Classes',
        'Attendance %',
        'Exam Eligibility Standing'
      ]
    ];

    items.forEach((item) => {
      csvRows.push([
        item.roll,
        `"${item.name.replace(/"/g, '""')}"`,
        item.section,
        `"${item.department}"`,
        item.subjectCode,
        `"${item.subjectName.replace(/"/g, '""')}"`,
        item.totalClasses,
        item.attendedClasses,
        item.absentClasses,
        `${item.percentage}%`,
        item.standing
      ]);
    });

    const csvContent = '\uFEFF' + csvRows.map((r) => r.join(',')).join('\r\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    link.href = url;
    link.setAttribute('download', `SREC_All_Candidates_Attendance_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-1.5 text-xs font-bold text-blue-700 bg-blue-50 px-3 py-1 rounded-full border border-blue-200">
            <span>Faculty Analytics</span>
            <span>&bull;</span>
            <span className="font-mono">{facultyId}</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900">
            All Candidates Attendance
          </h1>
          <p className="text-xs sm:text-sm text-slate-500">
            Subject-wise &amp; class section-wise aggregate attendance percentages and autonomous exam eligibility.
          </p>
        </div>

        <button
          type="button"
          onClick={() => exportCandidatesReport(filteredCandidates)}
          className="flex items-center gap-2 bg-emerald-700 hover:bg-emerald-800 text-white text-xs font-bold px-4 py-2.5 rounded-xl shadow-xs transition-transform active:scale-95 cursor-pointer shrink-0"
          title="Export all candidates attendance percentages to Excel"
        >
          <FileSpreadsheet className="w-4 h-4 text-emerald-300" />
          <span>Export Candidates Excel</span>
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-1">
          <div className="text-xs font-bold text-slate-500 uppercase flex items-center justify-between">
            <span>Total Candidates</span>
            <Users className="w-4 h-4 text-blue-600" />
          </div>
          <div className="text-2xl font-black text-slate-900">{totalCandidatesCount}</div>
          <div className="text-[11px] text-slate-500">Enrolled across selected subjects</div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-1">
          <div className="text-xs font-bold text-slate-500 uppercase flex items-center justify-between">
            <span>Average Attendance</span>
            <CalendarCheck className="w-4 h-4 text-emerald-600" />
          </div>
          <div className="text-2xl font-black text-emerald-700">{avgAttendance}%</div>
          <div className="text-[11px] text-slate-500">Autonomous threshold: 75% minimum</div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-1">
          <div className="text-xs font-bold text-slate-500 uppercase flex items-center justify-between">
            <span>Good Standing (&ge;75%)</span>
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
          </div>
          <div className="text-2xl font-black text-emerald-600">{goodStandingCandidates.length}</div>
          <div className="text-[11px] text-emerald-700 font-medium">Eligible for Semester Exams</div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs space-y-1">
          <div className="text-xs font-bold text-slate-500 uppercase flex items-center justify-between">
            <span>Shortage Risk (&lt;75%)</span>
            <AlertTriangle className="w-4 h-4 text-red-600" />
          </div>
          <div className="text-2xl font-black text-red-600">{shortageCandidates.length}</div>
          <div className="text-[11px] text-red-700 font-medium">Condonation / Detention Alert</div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex flex-wrap items-center gap-3">
          {/* Subject Filter */}
          <div className="space-y-1">
            <label className="text-[11px] font-bold text-slate-600 flex items-center gap-1">
              <BookOpen className="w-3.5 h-3.5 text-slate-400" />
              <span>Filter Subject</span>
            </label>
            <select
              value={selectedSubjectFilter}
              onChange={(e) => setSelectedSubjectFilter(e.target.value)}
              className="text-xs font-semibold p-2 rounded-xl border border-slate-200 bg-slate-50 focus:bg-white transition-colors"
            >
              <option value="ALL">All Subjects</option>
              {AVAILABLE_SUBJECTS.map((s) => (
                <option key={s.code} value={s.code}>
                  {s.code} - {s.name}
                </option>
              ))}
            </select>
          </div>

          {/* Class Section Filter */}
          <div className="space-y-1">
            <label className="text-[11px] font-bold text-slate-600 flex items-center gap-1">
              <Layers className="w-3.5 h-3.5 text-slate-400" />
              <span>Filter Section</span>
            </label>
            <select
              value={selectedSectionFilter}
              onChange={(e) => setSelectedSectionFilter(e.target.value)}
              className="text-xs font-semibold p-2 rounded-xl border border-slate-200 bg-slate-50 focus:bg-white transition-colors"
            >
              <option value="ALL">All Class Sections</option>
              <option value="CSE-III-A">CSE-III-A (Section A)</option>
              <option value="CSE-III-B">CSE-III-B (Section B)</option>
              <option value="CSM-III-B">CSM-III-B (AI &amp; ML)</option>
            </select>
          </div>
        </div>

        {/* Candidate Search */}
        <div className="relative w-full sm:w-72">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search candidate name or roll..."
            value={candidateSearch}
            onChange={(e) => setCandidateSearch(e.target.value)}
            className="w-full pl-9 pr-3 py-2 rounded-xl border border-slate-200 text-xs focus:border-blue-600 outline-hidden bg-slate-50 focus:bg-white"
          />
        </div>
      </div>

      {/* Candidates Attendance Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-700 font-bold">
              <tr>
                <th className="p-3.5">Roll Number</th>
                <th className="p-3.5">Candidate Name</th>
                <th className="p-3.5">Class Section</th>
                <th className="p-3.5">Subject</th>
                <th className="p-3.5">Attended / Total</th>
                <th className="p-3.5">Attendance Percentage</th>
                <th className="p-3.5 text-right">Autonomous Eligibility</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-medium">
              {filteredCandidates.length === 0 ? (
                <tr>
                  <td colSpan={7} className="p-8 text-center text-slate-400 text-xs">
                    No candidates match the selected filters.
                  </td>
                </tr>
              ) : (
                filteredCandidates.map((c) => (
                  <tr key={c.id} className="hover:bg-slate-50/70">
                    <td className="p-3.5 font-mono font-bold text-blue-900">{c.roll}</td>
                    <td className="p-3.5 font-bold text-slate-900">{c.name}</td>
                    <td className="p-3.5">
                      <span className="bg-slate-100 text-slate-700 font-mono text-[11px] px-2 py-0.5 rounded-md font-semibold border border-slate-200">
                        {c.section}
                      </span>
                    </td>
                    <td className="p-3.5">
                      <div className="font-semibold text-slate-800">{c.subjectName}</div>
                      <div className="text-[10px] text-slate-400 font-mono">{c.subjectCode}</div>
                    </td>
                    <td className="p-3.5 font-mono text-slate-700">
                      <span className="font-bold text-slate-900">{c.attendedClasses}</span> / {c.totalClasses} classes
                    </td>
                    <td className="p-3.5">
                      <div className="flex items-center gap-3">
                        <div className="w-24 bg-slate-200 rounded-full h-2.5 overflow-hidden">
                          <div
                            className={`h-full rounded-full transition-all ${
                              c.percentage >= 85
                                ? 'bg-emerald-500'
                                : c.percentage >= 75
                                ? 'bg-amber-500'
                                : 'bg-red-500'
                            }`}
                            style={{ width: `${Math.min(c.percentage, 100)}%` }}
                          />
                        </div>
                        <span
                          className={`font-mono font-black text-xs ${
                            c.percentage >= 85
                              ? 'text-emerald-700'
                              : c.percentage >= 75
                              ? 'text-amber-700'
                              : 'text-red-600'
                          }`}
                        >
                          {c.percentage}%
                        </span>
                      </div>
                    </td>
                    <td className="p-3.5 text-right">
                      {c.standing === 'ELIGIBLE' && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-bold bg-emerald-100 text-emerald-800 px-2.5 py-1 rounded-lg border border-emerald-200">
                          <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                          <span>Eligible</span>
                        </span>
                      )}
                      {c.standing === 'CONDONATION' && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-bold bg-amber-100 text-amber-900 px-2.5 py-1 rounded-lg border border-amber-300">
                          <AlertTriangle className="w-3 h-3 text-amber-700" />
                          <span>Condonation Required</span>
                        </span>
                      )}
                      {c.standing === 'DETAINED' && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-bold bg-red-100 text-red-900 px-2.5 py-1 rounded-lg border border-red-300">
                          <XCircle className="w-3 h-3 text-red-600" />
                          <span>Detention Risk</span>
                        </span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
